kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgCDD9Oc+2LIBZH1uYtuub/+KCdEmb7mqk8CK3f2GxtFPfkRKZVH8oVebT0K0WbSJsPcxadkSWvPN0gzNdqRCaOoCsCdeuS8dHdXlAxcOXkylULa+8cU8ZVRZ6WVbMTDrOY5vU3vVljZaTqx1JhqKkO+ggT3BqB8It/iIN/7WhO+M/d20Xd+e4AbUJCeSkTN2dW1U3zeQpYWCZYeu9kFaGC0nX7gqAiKQ1EgMuILdYTyBsUYu3lq7cfxSWakv7QIWbXOq/ntQ6bz0mAQhFag4ocIo7i7uhgxV3hEz7sLmhIFlvlyeb9M9nTT3d3vr4PCBXnPFzYmhWrU5yUFIp5E2q03fblz0pbU5vpjBwsc6dbtfhI9KznGHRQJFu3vNWem7gbh+RyOV1wj5ihWyf0BVmTvoVtpgoXGYlgaBygJp/+CRuqI0rf0VClnQXp7pXmhGOkqo0KpX8O3k+CP4dojzLfwsGNUsXHmb1/cNngBKP++nj/u4wcLNbfTD+OOY5+n4cTJt6k9WtdwEse2YuiVLBHUaWSQdg0KMBrso2y/OSzGndnDHlTDY8WUpotJjK0wV5c/N4tjQ/BHzFG4qv8oeztjv//XwhqWaIHdvfngB3r4EVfp0fFOnds+Joy1wJfbZtYPiQ7U//0dQXmXkGiqyHtBbxHpGV3bQRbMD18JwxIESwdGxeggRR97S2czSJ9bBOIFbxzDAxVrtHrq7y7PdSu5y2xcA9LeFMIrnSprFsBLxQ==
    postgresql-postgres-password: AgCx9//7J5ZCjrwTSh22IFuBTWmDDx30cjEyDafpENG5vCsprvoW8SxCvnw+vnnVkCaYsBP5V0I2LVTmQvqDJJcqYv6mnF5bfzBvLhvOm9i3EMjzTRPsv2sS8iU/p8mIXR0smHf8RATBj+l8VG5Ge0txBE1njle1TqLqUM42gLYn/W4OaNwkJiQy+KncIuigq/9nCZqnmfiWl4K90GaH1d5nKiht7z+NBZqsLJCk/lGIc4nztP+/XAKDzclhwHAgdyHh5eW52LfJJ/aezoNxjRb8aNZs07+1g6lhK1yymMAaJ4aYmOZGtSFaz+uduC3fLH8En8HUp+JBZesch3353VKnIRZSoou3GrW0FfGJGsxujmrIj6mbILzTpGIegn4bHUlQyACIq4H3Bc3bGsrIanMXmhMtfrox2BjHTD1T+Y+CfO3vPucx7XypIzMCKO64ll2pqRAQ43krfgti5J5TkzUIiWbese2n6fNtNAdLK+6/aEs1icJgSNjW6yL0L1OzrACT931sgUzK23+EBoYxFffAXaGr8LJ7PPkW6gM3NW4VVle3rsLkcK2GjoAKYuMYtpE0bzQNXR79u0QDA3CeuhC1Nu0TkeeIpuomhD/R9Gv/7xnPOm6h31p+WqWzzjPEh567/aPj10qsXmB+IY08h0w7vPCxVc/chHWFkfyigZWC9oy4ErUycyaqHl4hgeNZY1gciqLERFp2lgebic7keOg/eaoUJtM6div0fZywfNfmLA==
