kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgB3v3x7wgFaMrYf4nsE/i4Y5aA7xB2p41UC2GIVijwETyl+WUFqON8iChUd89yENnZrx6tpqmUhFpb9qFcbNXv3811sR3m6/n/nm057zhh2sB/Ous5P5Sb0OZXrkaaYORhooNhqMqM/ixx9OpJHX8NSwhuQKEH8GFe3xrlGt3Th7oloSciXKtuSrcQ58Jw9dSSeUe3GPx+k1r4vfj7qWw+/RckfCZeDHn4QWmD6/89gNwVrbkTJmqlUYV8BDo+XXuKmVeaZJcPraaMBzcktqLf06r0sYDvaMT5PHYi6KHePonhyrNpN8JDBYIY8JftDuZ7p3vUAxGxsEMEO4L/XiNd5IB/HwAa3TiTvkmGHaJ3Utrj9zerAIBBQ0IjwiVeVV+mJg+EFEsSxalAwm13cL1nF4vjcyXnSD/LJFXjPEh9CPPp3XkuvGUxrK2D+sTSNFtHFNR+yrymKvKg8LtZKkn8cO2qKprh1WFvUmfHH52htY/A6tpKohyA7YIT5a8+Ul5Z3AfFBbauftMliM8XHwqIGUvVcZLa6gcgFgkPecLn7yYQHz1Rawr/wR/9UUWLFMeKKLzqEYwjX0cVg7QZjQGe4GDSM8IANEo4fD7cqFn4AhWgk7h+feDQCCpkDx7/Z4nAo5ah90nVKW4/acDCNdc/r3UCihAe9r1IU+uaNn6L3frHltdPPzfY5d6UJ2j8+n15VNfKp+iULJvtPP5tVUYmI
    admin-user: AgAXQQ1kiYuhKao97c2cTwymtUTfNjJfxtqpixN4sYlZiND5iiP0HzRAz/kAnL1SzQGLX+/deqXmK2bB2TmYAnfBdwLYBwpcQ6nNr/YI3WdtqAxF3oE0er13KQ6Cct9MtP1O+6Cm9sFuYH6p4pSWQfVpKXwo1Xqbn56rrOLNzCcPD3Mm/oldfJmgFo70bvsOMqRmleSOgFei0xrSHNdX25X0cghjCuEgIhBuboDFnE5KTHYjFEMa5ns3rBoWPnyFNLAp3uC45HJlnTj6wbliycFO38Y4dt28zxwzhr9UgkgkTCQc2N422oEoVkJktLe18uLPWr+9nVkYVqlF9o7OTekXlVb3PVCtjou/SoH25dThJTSw7tm301Di12KmdUvNvpPxLvhmQuFtGYVrOGSFG722dbfXrL5Ur/9zj1egwjSzVWxBm8rUZgeCL5zlUHOX8vMkcCxzyjKKs4a7N5Si2gCFGTj6If5sLDnWM/HGJN7/0xcIoxk8QTJin+Wa6+1TDMGAIh6A5S3MslP2mzLtFM5YTY9qN8aDs5nkwSBLJn7/cFoZn9z/Eu6cAjTvhWkDndMhSoAYbYd2xKb9yInsUEPQlsHpFyteBZ7HQ2qy8DqcpbPzYninSznueUJFfZFWrPh8qvA2daeMaV39yzoZf1ZhtVDHf3KkTwlhl/dwfAy8zEOt0nGLEjfwfThPMIVtpMajd6pMYLeRbKRp
